### ISSUE TITLE
API incompatibility 3.8/3.9

### ISSUE THREAD

**Issue by Natureshadow** [python/importlib_metadata#254]
This package states that it is a backport of Python 3.8's `importlib.metadata` module and is API-compatible. This is not true — for example, Python 3.9's `EntryPoint` objects has attributes `module` and `attr`. This backport has this API, while Python 3.8's API doesn't.

The documentation should be more detailed on whe nto use this package and when not, and what API it really mimics.

**Comment by jaraco** [comment]
Thanks for the report. As you can see in 216397d, I've updated the documentation to describe the situation. This project typically releases functionality early, before it is released in future Python versions, so it represents a continuous backport. Not a lot has changed since Python 3.8 that wasn't ported back to Python 3.8, as you can see from the [changelog](https://importlib-metadata.readthedocs.io/en/latest/changelog%20%28links%29.html).

Put another way - if you need the behavior from the latest Python release, then you'll need to use the backport in any earlier Python release. If you use features slated for the next Python release, then you'll need the backport for the current Python release. But if you're able to rely on the Python 3.8 implementation, then you only need the backport for Python 3.7 and earlier.

I notice the Python docs don't indicate that the ``module`` and ``attr`` were added in Python 3.9, but I do see that they're not mentioned in the [Python 3.8 docs](https://docs.python.org/3.8/library/importlib.metadata.html#entry-points). Could be a better user experience around those details.
