### ISSUE TITLE
Need more type definitions

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#288]
In [this twine commit](https://github.com/pypa/twine/pull/736/commits/0a2111fe4587da1bcf0d43e272fc738e45cdb081), I learned that twine in unsatisfied with the type declarations and needs more hand holding.

**Comment by bhrutledge** [comment]
My general interpretation is that `importlib_metadata` has a lax mypy configuration:

https://github.com/python/importlib_metadata/blob/aa9f799bda305bfb4fd51e4dba230207267aecd6/mypy.ini#L1-L2

which could cause errors in any project that has a more strict configuration (like [Twine](https://github.com/pypa/twine/blob/d01fdfa54d1614d1b949ba12f0f6475cec697ca0/mypy.ini#L4-L19)). Since this is a core library, putting the effort into satisfying a strict mypy configuration could bring value to lots of projects.

**Comment by janosh** [comment]
> satisfying a strict mypy configuration could bring value to lots of projects.

Sounds like @asottile would be exactly the right guy for the job. 😄

**Comment by jaraco** [comment]
This issue is open-ended and partially-complete. I'm closing it, but let it be known that I welcome improvements to the type declarations, especially those improvements that add clarity and information that would otherwise be undiscoverable or difficult to discover.
