### ISSUE TITLE
`importlib.metadata.version` and `pip` disagree about versions

### ISSUE THREAD

**Issue by bdraco** [python/importlib_metadata#291]
Consider the following 

```
home_assistant_frontend-20210226.0.dist-info
home_assistant_frontend-20210226.0.dist-info/INSTALLERxne2hz8x.tmp
home_assistant_frontend-20210302.6.dist-info
home_assistant_frontend-20210302.6.dist-info/LICENSE.md
home_assistant_frontend-20210302.6.dist-info/METADATA
home_assistant_frontend-20210302.6.dist-info/WHEEL
home_assistant_frontend-20210302.6.dist-info/top_level.txt
home_assistant_frontend-20210302.6.dist-info/INSTALLER
home_assistant_frontend-20210302.6.dist-info/RECORD
```

Above `home_assistant_frontend-20210226.0` fails to fully install and then `home_assistant_frontend-20210302.6` was installed.

```python
Python 3.8.3 (default, Jul 10 2020, 17:15:14) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from importlib.metadata import version
>>> print(version('home-assistant-frontend'))
None
>>> 
```

At this point `version` will return `None` but pip will tell us its up to date

```
Requirement already up-to-date: home-assistant-frontend in /usr/local/lib/python3.8/site-packages (20210302.6)
```

I'm not sure what the best resolution for this issue is as it seems to come up more frequently then one would expect given 

https://github.com/home-assistant/core/issues/47699

**Comment by jaraco** [comment]
My guess here is `version('home-assistant-frontend')` is returning `None` because `home_assistant_frontend-20210226.0.dist-info` exists and has no metadata.

I tried to replicate the situation thus:

```
draft $ pip install --use-pep517 --no-deps -t . home-assistant-frontend==20210302.6 -q
draft $ mkdir home_assistant_frontend-20210302.0.dist-info
draft $ tree -L 2
.
├── hass_frontend
│   ├── __init__.py
│   ├── __pycache__
│   ├── authorize.html
│   ├── frontend_es5
│   ├── frontend_latest
│   ├── index.html
│   ├── onboarding.html
│   ├── robots.txt
│   ├── service_worker.js
│   └── static
├── home_assistant_frontend-20210302.0.dist-info
└── home_assistant_frontend-20210302.6.dist-info
    ├── INSTALLER
    ├── LICENSE.md
    ├── METADATA
    ├── RECORD
    ├── REQUESTED
    ├── WHEEL
    └── top_level.txt

7 directories, 13 files
```

But when I tried to load the metadata, it found the version:

```
draft $ env PYTHONPATH=. python
Python 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:06:10) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib.metadata as md
>>> md.version('home-assistant-frontend')
'20210302.6'
```

But it's not a huge surprise that since there are apparently two versions of the same package present in the metadata that the behavior would be unusual. Querying for all distributions by that name, two appear:

```
>>> list(md.Distribution.discover(name='home-assistant-frontend'))
[<importlib.metadata.PathDistribution object at 0x7fba13ea06a0>, <importlib.metadata.PathDistribution object at 0x7fba13ea0730>]
```

My guess is that on some systems, the 0 appears before the 6 and on others the 6 appears before the 0, and `importlib.metadata` just uses the first one it finds.

I'm not sure there's a lot this package can do when the metadata is corrupted as you've indicated.

Perhaps this package could consider excluding metadata directories that are missing key metadata (like METADATA), but that would make discovery more expensive, something this project has worked hard to optimize.

Perhaps better would be to identify the cause of the failed installations and prevent those or enhance the detection of failed installations and repair or clean up after those events.

**Comment by jaraco** [comment]
The fact that pip and importlib.metadata disagree is probably something that will be fixed as pip moves toward adopting importlib.metadata.

**Comment by bdraco** [comment]
> The fact that pip and importlib.metadata disagree is probably something that will be fixed as pip moves toward adopting importlib.metadata.

Thanks for looking.

It is likely that the lack of atomicity with the pip install will need to get solved once pip switches over because it is will come up in the normal course given how prevalent we see it in Home Assistant.  We have worked around the cruft in https://github.com/home-assistant/core/pull/47706 and will likely revert that once pip adopts import lib and makes whatever adjustments are needed.
