### ISSUE TITLE
Entrypoint __iter__ implemementation breaks _asdict

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python/importlib_metadata#337]
https://github.com/python/importlib_metadata/blob/2678a5e5af2c459cd5c9246e38f8cfd9213004fe/importlib_metadata/__init__.py#L191-L200

```
#debug from usage of the stdlib copy
(Pdb) v
EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm')
(Pdb) v._asdict()
{'name': '.git', 'value': EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm')}
(Pdb) type(v)
<class 'importlib.metadata.EntryPoint'>
(Pdb) v._fields
('name', 'value', 'group')
(Pdb) 

```

i was most surprised when my namedtuple debug printer turned into a endless recursion

**Comment by jaraco** [comment]
Also [bpo-44893](https://bugs.python.org/issue44893).

**Comment by jaraco** [comment]
In #338, I've drafted a fix, but  before I merge the change, I'm pondering - does this project want to support the requested interface. I agree that it's reasonable to expect a `namedtuple` subclass to implement all the features of a namedtuple. This subclass, however, explicitly _overrides_ the default expectation that `__iter__` returns the values... and it was never the explicit intention that `EntryPoint._asdict` should work.

I originally made `EntryPoint` a subclass of a namedtuple as a shorthand to describe an object with three properties. I never intended it to be used as a tuple or namedtuple.

I've only learned in the past couple of years how dangerous it is to use a built-in type because it implements a subset of the features needed. In a formal API such as `importlib.metadata` exposes, it's important to be explicit about the minimum surface supported by the API... and using built-in types implicitly exposes a good deal of extraneous, sometimes unwanted functionality, violating the "preferably only one" obvious way.

Before embarking on supporting the requested behavior, I think it's worthwhile stepping back to ask - what is this functionality needed for?

Other approaches I'd like to consider:

- Drop `namedtuple` as a base class and instead implement a "simple object with 3 properties" (possibly providing compatibility for behaviors that could be relied upon in the current implementation).
- Drop support for non-working or unwanted `namedtuple` behaviors (through `NotImplementedError` or `AttributeError`s).

Why should this project care about supporting `_asdict()`?

**Comment by RonnyPfannschmidt** [comment]
its a easy way to debug/trace details for namedtuples (where vars won't work)

in my own code i migrated to always use fields/getattr to wokr around the bug

i took note of the issue when it created a endless recursion in a debug helper

its not clear to me what most reasonable way to express a entrypoint would be,
its really unfortunate the __iter__ "convenience" exists in the first place

imho it violates multiple python principles just to provide convenience,

**Comment by jaraco** [comment]
> its really unfortunate the **iter** "convenience" exists in the first place

That I can agree, and that behavior is deprecated and slated for removal.

> its a easy way to debug/trace details for namedtuples (where vars won't work)
> 
> in my own code i migrated to always use fields/getattr to wokr around the bug
> 
> i took note of the issue when it created a endless recursion in a debug helper

Thanks for clarifying. That doesn't strike me as a particularly compelling reason to keep this particular interface and more a reason to get rid of the qwirky `__iter__` and excess `namedtuple` behaviors. If the debug helper is a one-off, a one-off workaround seems appropriate. If the debug helper is built into an ecosystem like pytest or Pycharm or similar, that to me is a much stronger case to find a solution.

In #339, I lay out the implementation I have in mind. Basically, eschew namedtuple and instead store keyword-only attributes on the object. The `__iter__` hack is still there and still deprecated.
