### ISSUE TITLE
Broken mypy support

### ISSUE THREAD

**Issue by chrisjsewell** [python/importlib_metadata#351]
Heya, after this commit: https://github.com/python/importlib_metadata/commit/29ec9c38dd5390f7d4326d2c792b4e49a9d0e334,
mypy (and I imagine other static analysers) can no longer determine that the `EntryPoint` has `name`, `value` and `group` attributes.

Was there a reason for doing this:

```python
    def __init__(self, *, name, value, group):
        vars(self).update(name=name, value=value, group=group)
```

rather than the conventional

```python
    def __init__(self, *, name, value, group):
        self.name = name
        self.value = value
        self.group = group
```

**Comment by jaraco** [comment]
> Was there a reason for doing this

Yes. You can try making that change and you'll see the tests fail. `__setattr__` is overridden to make the object immutable.

I'd really like to see the mypy add support similar to `NamedTuple` for this use-case.

Do you know of a way to fix this issue? I know in #342, Anders is working on enabling strict type checking on this project. But that issue is currently blocked on mypy being unable to support dynamic constructs like `always_iterable` and rebasing on this recent refactor.

Perhaps the reported issue here could be solved by adding type directives to the class properties, but without a repro, I'm not even sure how to test for expected behavior.

Feel free to follow up with a repro or proposed patch. In the meantime, I'll close this as answered.
