### ISSUE TITLE
zipp library minimum version should be bumped

### ISSUE THREAD

**Issue by ralonsoh** [python/importlib_metadata#385]
According to zipp [1] compatibility matrix, for stdlib 3.8, the minimum required version is 1.0

This project is requesting > 0.5

[1]https://pypi.org/project/zipp/

**Comment by jaraco** [comment]
I'm not sure I understand your logic. Yes, zipp 1.0 was the version released with Python 3.8, but this package supports Python 3.7 (and earlier releases support Python 2.7 and 3.5+). 

From my perspective, all that matters is that this project declares the minimum version required to function, though there may be benefits (performance or otherwise) to load a more recent version.

When I run the tests on Python 3.10.4 against zipp 0.5, the tests all pass, leading me to believe this package is still compatible with `>=0.5`.

Can you elaborate why this package should bump the version and to what minimum version?

**Comment by jaraco** [comment]
Closing without prejudice. Happy to revisit.
