### ISSUE TITLE
Apache license incorrectly applied

### ISSUE THREAD

**Issue by tlandschoff-scale** [python/importlib_metadata#387]
Hi all,

during a license review I came across `importlib_metadata` which appears to be required by one of our third-party packages (actually it gets pulled by setuptools).

Looking at the file LICENSE I found this:

> you may not use this file except in compliance with the License.

Which would make much more sense if applied to individual source files :wink: 

In fact, https://www.apache.org/licenses/LICENSE-2.0.html#apply states:

> Include a copy of the Apache License, typically in a file called LICENSE, in your work, and ...

IMO this means that the file `LICENSE` should be a verbatim copy of https://www.apache.org/licenses/LICENSE-2.0.txt

The file `NOTICE` should mention the copyright owner and the individual source files would carry the boiler plate currently included as `LICENSE` file. This is how apache httpd does it:

* [LICENSE file](https://github.com/apache/httpd/blob/d3d3c599def0bd261b26c68ac60f4e02310fd52c/LICENSE)
* [NOTICE file](https://github.com/apache/httpd/blob/d3d3c599def0bd261b26c68ac60f4e02310fd52c/NOTICE)
* [main.c source](https://github.com/apache/httpd/blob/d3d3c599def0bd261b26c68ac60f4e02310fd52c/server/main.c)

If you like, I'll be glad to open a pull request.

Greetings, Torsten

**Comment by jaraco** [comment]
This project is based on jaraco/skeleton. For more information on my opinion on license files, see https://github.com/jaraco/skeleton/issues/1. I really don't want to spend a lot of time fussing about the license.

This project (and importlib_resources) use the Apache 2.0 license based on the preference of warsaw. My preference would be to simply license it under MIT.

At first, I thought you were mistaken, that the Apache 2.0 guidance indicated to put the small boilerplate in the LICENSE file, but now that I read it again, I think you may be right, that the full text of the license should be included in the file. I'm not interested in littering the rest of the repo or files with licensing details, especially since the source files are synced with CPython and relicensed under the PSF license.

Moreover, external sources seem to agree that the license as supplied is adequate enough to recognize the correct license:

[<img width="279" alt="image" src="https://user-images.githubusercontent.com/308610/173975679-f7ea8ac4-8464-4be5-8c35-2ba4c2b8e519.png">](https://pypi.org/project/importlib-metadata/)

I'm on the fence as to whether or not to replace the content of the license file with the full license text. I guess it's more proper to have the full text (and more correct not to mention "this file"). So I'll proceed to make that change.

**Comment by tlandschoff-scale** [comment]
Hi Jason,

thanks for putting the full license file in there.

I agree that this legal stuff is a pain in the ass. I'd rather be coding.

> I'm not interested in littering the rest of the repo or files with licensing details

As I understand it this is not required as the same license applies to the whole bundle.

Greetings, Torsten
