### ISSUE TITLE
How to check if a requirement is met without pkg_resources

### ISSUE THREAD

**Issue by HansBug** [python/importlib_metadata#450]
In our work, we need to use the Python source code to check if the dependencies specified in requirements.txt are fully satisfied. Previously, we used `pkg_resources.require` like this (https://stackoverflow.com/a/16298328/6995899 ), but now that it has been deprecated, how can we achieve the above functionality in new packages?

**Comment by jaraco** [comment]
importlib metadata doesn't provide this functionality. It seems that [packaging](https://pypi.org/project/packaging) does not either. Someone will need to write that functionality, and since it probably will depend on `packaging`, it probably should be in that package or in something that can depend on it (importlib metadata cannot because it's part of stdlib). This issue has been reported in https://github.com/pypa/packaging-problems/issues/317.

**Comment by jaraco** [comment]
Glad you found a solution. You may want to post that over in packaging-problems, as that will help a wider audience.

**Comment by HansBug** [comment]
> Glad you found a solution. You may want to post that over in packaging-problems, as that will help a wider audience.

Posted https://github.com/pypa/packaging-problems/issues/664
